### ISSUE TITLE
你好，能否提供一份没有压缩过的js文件

### ISSUE THREAD

**Issue by ww380459000** [amazeui/docs#1]
你好，能否提供一份没有压缩过的js文件？谢谢

**Comment by Minwe** [comment]
你要哪个文件的？

**Comment by ww380459000** [comment]
main的，可以的话把你们自己写的提供一下，除了那些核心包，谢谢

**Comment by Minwe** [comment]
https://gist.github.com/Minwe/9f7efada432e5965e0e9

**Comment by Minwe** [comment]
上面就是 main.js 源码 browserify 后的结果。

**Comment by ww380459000** [comment]
我这被墙了，有其他办法发给我吗？谢谢

**Comment by ww380459000** [comment]
可以了，谢谢
